name: build and deploy
permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v1

      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: build
        run: just build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build

      - name: update readme
        run: sed -i 's/sha512-.*$/sha512-'$(shasum -a 512 build/config/setup.ign | awk '{print $1}')'/' README.md

      - name: commit & push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update readme with latest hash"
